#server:
  #port: 8081
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/1609a
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
    # 通用mapper已经提供了驼峰转换的设置，所以可以不用再设置
      configuration:
        map-underscore-to-camel-case: true